### ISSUE TITLE
Allow for themes

### ISSUE THREAD

**Issue by coastalwhite** [coastalwhite/lemors#7]

**Comment by danielgafni** [comment]
Hey, I might be interested in working on this. What do you think?

**Comment by coastalwhite** [comment]
Hello Daniel,

That would be wonderful. I added a bit of what I envision this to be as the description of this issue. It essentially comes down to replacing some of the values after the configuration has been parsed. I guess that this should only require changing `src/config.rs`. If you have any questions, please let me know.

**Comment by danielgafni** [comment]
Do you think we should support a separate `theme.toml` file for easier themes sharing?

**Comment by coastalwhite** [comment]
That is actually a really good idea. I am not sure how we should incorporate #67 into this. For now, just having a `theme.toml` is great.

**Comment by danielgafni** [comment]
I'm thinking to introduce a new top-level struct: `ConfigsCollection` for this purpose. 

The old `Config` would be one of it's fields. Another field would be `Theme`. 

Is this the right way to think about it?

**Comment by coastalwhite** [comment]
I think we could resolve this immediately when `Config` is created. This way the rest of the program doesn’t have to deal with the consequences of introducing a new layer of abstraction.

When, we load the configuration we load the theme as well and replace the corresponding configuration values immediately.

**Comment by danielgafni** [comment]
So you want to have the `theme` section in the main config and override it from a `theme.toml` file if it exists?

**Comment by coastalwhite** [comment]
I added a bit more detail to the main description.

Basically, the user can specify a `[theme]` section or have a `theme.toml` file in `/etc/lemurs`. If they are both present, use the `theme.toml` file. Probably also log a `warn!`.

**Comment by danielgafni** [comment]
Hey!

1. Which parameters do we want to include into `theme.toml`? For now I'm only including the colors. 
2. Should we keep the old parameters? If so, what is the best place to replace their values from the new theme parameters? Is it `main.rs` right after `config` is created?

**Comment by coastalwhite** [comment]
Just colors and parameters is fine for now. I think we just have a general set of variables, and then the default configuration references those variables.

An example user-configuration (`theme.toml`) would be

```toml
border = "white"
border-active = "orange"
# ...
```

The default configuration would then include:

```toml
# ...

[username_field.style]
border_color = "${theme.border}"
border_color_focused = "${theme.border_focused}"

[password_field.style]
border_color = "${theme.border}"
border_color_focused = "${theme.border_focused}"
```
